# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            '桃花岛东邪' 
tagline:          'Cocos Creator, 开发者'
description:      '归去来兮，田园将芜胡不归？'
url:              http://cocoscloud.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/joewan

theme: jekyll-theme-slate
